
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupons_ms_spring?serverTimezone=UTC&createDatabaseIfNotExist=true&jdbcCompliantTruncation=false&sslmode=require
    username: DEV_USER
    password: qwjf2674h^dk234$DEV

  devtools:
    restart:
      enabled: true

  jpa:
    properties:
      hibernate:
        ddl-auto: create-only
        show_sql: true
