
spring:
  datasource:
    url: jdbc:h2:mem:coupons_ms_spring?serverTimezone=UTC&createDatabaseIfNotExist=true&jdbcCompliantTruncation=false&sslmode=require
    username: sa
    password: password

  devtools:
    restart:
      enabled: true

  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
