info:
  application:
    name: coupons-as-art
    description: A mock for coupons management system
    author: Artur Farmanov
    version: '@project.version@'

#----------------- Spring config    -----------------
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:coupons_ms_spring?serverTimezone=UTC&createDatabaseIfNotExist=true&jdbcCompliantTruncation=false&sslmode=require
    driver-class-name: org.h2.Driver
    username: [YOUR_USERNAME]
    password: [YOUR_PASSWORD]

  jpa:
    open-in-view: false # disable the Open Session in View anti-pattern, inefficient from a database perspective

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        enable_lazy_load_no_trans: true # this is inefficient as it introduces n+1 problem
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  http:
    multipart:
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB

#----------------- Jackson config    -----------------
jackson:
  serialization:
    FAIL_ON_EMPTY_BEANS: false

#----------------- Server config    -----------------
server:
  error:
    include-message: always

image_folder_path: src\/main\/resources\/images\/coupons\/
