package com.fa.CouponsMsProject.utils.generators;

public enum AvailableCompanyNames {

    TEMPEST_HOTELS, TALISMAN_HOTELS,

    EPIC_TRAVEL, TRAVEL_OCITY,

    PIONEER_TOOLS, TOOL_SCOUT,

    NEBULA_ELECTRONICS, ELECTRONICS_SUPPLY,

    SUCCESS_HOUSEHOLD, AMIGO_HOUSEHOLDS,

    VACATION_BOOST, ROCKSTAR_VACATIONS,

    CHEETAH_AUTOMOTIVE, AUTOMOTIVE_CANDY,

    RESTAURANT_VENUE, CLOUD_TASTE,

    BABY_JAR, BABY_DEPT,

    VIVA_GROCER, GROCERY_SAFARI,

    FASHION_EAGLE, OUTFISTA,

    CARE_SHOP, TRUE_CARE,

    BRAVO_SOFT, SOFT_DOME,

    GODDESS_SHAWARMA,
    CONCERT_PLAZA,
    MESSI_STRIKE,
    MAGNUM_TATTOO,
    CALYPSO_WATER_PARK,
    NIFTY_JUMP
}
